# Generated by Django 5.2.16 on 2026-07-27

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("location", models.CharField(max_length=255)),
                ("registration_opens_date", models.DateField()),
                ("registration_closes_date", models.DateField()),
                ("registration_link", models.URLField(blank=True)),
                ("cost_per_team", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("organizing_company", models.CharField(blank=True, max_length=200)),
                ("team_minimum", models.PositiveIntegerField(default=0)),
                ("stay_to_play", models.BooleanField(default=False)),
                ("stay_to_play_link", models.URLField(blank=True)),
                ("stay_to_play_notes", models.TextField(blank=True)),
                ("coach_hotel", models.CharField(blank=True, max_length=200)),
                ("hotel_location", models.CharField(blank=True, max_length=255)),
                ("number_of_rooms", models.PositiveIntegerField(default=0)),
                ("cost_per_room", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("coaches_notes", models.TextField(blank=True)),
                ("travel", models.CharField(blank=True, max_length=200)),
                ("flight_number", models.CharField(blank=True, max_length=100)),
                ("number_of_coaches", models.PositiveIntegerField(default=0)),
                ("travel_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["start_date", "name"]},
        ),
        migrations.CreateModel(
            name="TournamentRegistration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_registered", models.BooleanField(default=False)),
                ("is_paid", models.BooleanField(default=False)),
                ("rosters_entered", models.BooleanField(default=False)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tournament_registrations",
                        to="tournaments.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("tournament", "team"), name="unique_tournament_team"),
                    models.CheckConstraint(
                        condition=~Q(("is_paid", True)) | Q(("is_registered", True)),
                        name="payment_requires_registration",
                    ),
                    models.CheckConstraint(
                        condition=~Q(("rosters_entered", True))
                        | (Q(("is_registered", True)) & Q(("is_paid", True))),
                        name="rosters_require_registration_and_payment",
                    ),
                ]
            },
        ),
    ]
