# Generated by Django 5.2.16 on 2026-07-29 18:57

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import coaches.models
import coaches.services


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(default=coaches.models.invitation_expiry)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_coach_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CoachProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("monthly_base_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "additional_hourly_rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__last_name", "user__first_name", "user__username"],
            },
        ),
        migrations.CreateModel(
            name="CoachMonthlyPayroll",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.DateField()),
                ("base_rate_snapshot", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_payrolls",
                        to="coaches.coachprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-month", "coach__user__last_name", "coach__user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="AdditionalWork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("club_practice", "Club practice"),
                            ("academy", "Academy"),
                            ("volley_tots", "Volley Tots"),
                            ("volley_jrs", "Volley Jrs"),
                            ("camp_clinic", "Camp/Clinic"),
                            ("private_lesson", "Private Lesson"),
                            ("tournament", "Tournament"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("work_date", models.DateField(default=coaches.services.central_today)),
                (
                    "hours_worked",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.5")),
                            django.core.validators.MaxValueValidator(Decimal("12")),
                        ],
                    ),
                ),
                (
                    "tournament_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("hourly_rate_snapshot", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("payment_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payroll_month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_items",
                        to="coaches.coachmonthlypayroll",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_items",
                        to="coaches.coachprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-work_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrivateLesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "children_coached",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("payment_amount", models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                (
                    "additional_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_lessons",
                        to="coaches.additionalwork",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="coachmonthlypayroll",
            constraint=models.UniqueConstraint(fields=("coach", "month"), name="unique_coach_payroll_month"),
        ),
        migrations.AddConstraint(
            model_name="additionalwork",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("hours_worked__isnull", True),
                    models.Q(("hours_worked__gte", Decimal("0.5")), ("hours_worked__lte", 12)),
                    _connector="OR",
                ),
                name="additional_work_hours_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="additionalwork",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tournament_days__isnull", True),
                    models.Q(("tournament_days__gte", 1), ("tournament_days__lte", 3)),
                    _connector="OR",
                ),
                name="additional_work_tournament_days_in_range",
            ),
        ),
    ]
