# Generated by Django 5.2.16 on 2026-07-30 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coaches", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="additionalwork",
            name="additional_work_tournament_days_in_range",
        ),
        migrations.AlterField(
            model_name="additionalwork",
            name="tournament_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AddConstraint(
            model_name="additionalwork",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tournament_days__isnull", True),
                    models.Q(("tournament_days__gte", 1), ("tournament_days__lte", 4)),
                    _connector="OR",
                ),
                name="additional_work_tournament_days_in_range",
            ),
        ),
    ]
