version: "3.8"

name: tournament_overview

services:
  db:
    image: postgres:16
    restart: "always"
    env_file:
      - ./envs/.env
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all" ]

  api: &app
    build:
      context: ../
      dockerfile: ./compose/services/Dockerfile
      target: "development_image"
      # secrets:
      #   - gitlab
    restart: "always"
    env_file:
      - ./envs/.env
    expose:
      - 8080
    # ports:
    #   - "192.168.0.52:18080:8080"
    depends_on:
      - db
      - setup
      - cache
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.tournament-overview.rule=Host(`tournament-overview.lab.ricehouse.me`)"
      - "traefik.http.routers.tournament-overview.entrypoints=websecure"
      - "traefik.http.routers.tournament-overview.tls.certresolver=cloudflare"
      - "traefik.http.services.tournament-overview.loadbalancer.server.port=8080"
    volumes:
      - "../:/app"
    stdin_open: true
    tty: true
    networks:
      - default
      - proxy

  setup:
    <<: *app
    depends_on:
      - db
    volumes: []
    labels: []
    environment:
      - LOAD_INITIAL_DATA=true
    command: [ "bash", "/app/compose/services/wait-for-it.sh", "db:5432", "--", "bash", "/app/compose/services/run-setup.sh" ]
    restart: on-failure

  cache:
    image: redis:alpine
    restart: always
    expose:
      - "6379"

  # celeryworker:
  #   <<: *app
  #   depends_on:
  #     - db
  #     - cache
  #   volumes: []
  #   ports: []
  #   labels: []
  #   command: [ "bash", "/app/compose/services/start-celery.sh", "-s", "worker" ]
  #   networks:
  #     - default

  # celerybeat:
  #   <<: *app
  #   depends_on:
  #     - db
  #     - cache
  #   volumes: []
  #   ports: []
  #   labels: []
  #   command: [ "bash", "/app/compose/services/start-celery.sh", "-s", "beat" ]
  #   networks:
  #     - default
  # celeryflower:
  #   <<: *app
  #   depends_on:
  #     - db
  #     - cache
  #   volumes: []
  #   ports: []
  #   expose:
  #     - 5555
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.flower_${COMPOSE_PROJECT_NAME}_http.rule=Host(`flower.tournament-overview.localhost`)"
  #     - "traefik.http.routers.flower_${COMPOSE_PROJECT_NAME}_http.tls=true"
  #     - "traefik.http.routers.flower_${COMPOSE_PROJECT_NAME}_http.entrypoints=websecure"
  #     - "traefik.docker.network=proxy"
  #   command: ["bash", "./compose/services/web/start-celery.sh", "-s", "flower"]
  #   networks:
  #     - default

volumes:
  db-data:


networks:
  proxy:
    external: true

# secrets:
#   gitlab:
#     file: ./envs/gitlab.env
